### ekf config file ###
ekf_node:
    ros__parameters:
# The frequency, in Hz, at which the filter will output a position estimate. Note that the filter will not begin
# computation until it receives at least one message from one of the inputs. It will then run continuously at the
# frequency specified here, regardless of whether it receives more measurements. Defaults to 30 if unspecified.
#frekvencija koliko puta u sekundi, ovde 30 ekf racuna novu procenu pozicije i orijentacije
        frequency: 30.0

# ekf_localization_node and ukf_localization_node both use a 3D omnidirectional motion model. If this parameter is
# set to true, no 3D information will be used in your state estimate. Use this if you are operating in a planar
# environment and want to ignore the effect of small variations in the ground plane that might otherwise be detected
# by, for example, an IMU. Defaults to false if unspecified.
#koristimo 3D model, ako je true onda se koristi 2D model
        two_d_mode: false

# Whether to publish the acceleration state. Defaults to false if unspecified.
#ekf moze da izracuna i ubrzanje, ako je true onda se to ukljucuje u izracunavanje pozicije i orijentacije robota i
#takodje se objavljuje na topic /odometry/filtered
        publish_acceleration: true

# Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
#ekf obavljuje i transformaciju izmedju odom i base_link frame-ova, TF-ovi omogucavaju da se zna gde se robot nalazi u prostoru i da RViz da se odatle vidi
        publish_tf: true

# 1. Set the map_frame, odom_frame, and base_link frames to the appropriate frame names for your system.
#     1a. If your system does not have a map_frame, just remove it, and make sure "world_frame" is set to the value of odom_frame.
# 2. If you are fusing continuous position data such as wheel encoder odometry, visual odometry, or IMU data, set "world_frame"
#    to your odom_frame value. This is the default behavior for robot_localization's state estimation nodes.
# 3. If you are fusing global absolute position data that is subject to discrete jumps (e.g., GPS or position updates from landmark
#    observations) then:
#     3a. Set your "world_frame" to your map_frame value
#     3b. MAKE SURE something else is generating the odom->base_link transform. Note that this can even be another state estimation node
#         from robot_localization! However, that instance should *not* fuse the global data.

#frame-ovi koje koristi ekf, map_frame je globalni koordinatni sistem, odom_frame je lokalni koordinatni sistem koji se pomera u odnosu na map_frame, base_link je koordinatni sistem robota
#world_frame je koordinatni sistem u kome zelimo da dobijemo poziciju i orijentaciju robota, ako fuziramo samo lokalne podatke (odometrija, IMU) onda je world_frame isti kao odom_frame
#ako fuziramo globalne podatke (GPS, landmark) onda je world_frame isti kao map_frame i moramo da obezbedimo da nesto drugo (npr. drugi ekf) generise odom->base_link transformaciju 
        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified


# ekf je subscriber na enc_odom i imu topic-ove
        odom0: /enc_odom
        #ovde su true sve one vrednosti koje zelimo da ekf koristi iz enc_odom poruka
        #redom su: x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az , EKF koristi linearne brzine vx, vy i uglovnu brzinu yaw.
        odom0_config: [false, false, false,
                      false, false, false,
                      true, true, false,
                      false, false, true,
                      false, false, false]

        imu0: /imu
        #ovde su true sve one vrednosti koje zelimo da ekf koristi iz imu poruka
        #redom su: x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az , EKF koristi samo yaw orijentaciju i az ubrzanje iz IMU poruka
        imu0_config: [false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, true,
                      false, false, false]