# Locks to stop the twist inputs.
# For each lock:
# - topic   : input topic that provides the lock; it must be of type std_msgs::Bool?!!!
# - timeout : == 0.0 -> not used
#              > 0.0 -> the lock is supposed to published at a certain frequency in order
#                       to detect that the publisher is alive; the timeout in seconds allows
#                       to detect that, and if the publisher dies we will enable the lock
# - priority: priority in the range [0, 255], so all the topics with priority lower than it
#             will be stopped/disabled
# - expire_on_idle: If true, it will expire in command is zero
#                   TRUE - lock se automatksi iskljuci kad poruke prestanu da stizu
#                   FALSE - ostaje aktivan dok se ne dobije "eksplicitna" poruka da je otkljucan

twist_mux:
  ros__parameters:
    locks:
      pause:
        topic   : pause_navigation
        timeout : 0.0
        # Same priority as joystick control, so it'll not block it.
        priority: 100
        expire_on_idle: false 
      loop_closure:
        topic   : stop_closing_loop
        timeout : 0.0
        priority: 200
        expire_on_idle: false
      joystick :
        topic   : joy_priority
        timeout : 0.0
        priority: 100
        expire_on_idle: false
