joy_node:
    ros__parameters:
        device_id: 0 #prvi uredjaj prepoznat od strane OS-a
        device_name: "''" #inace koristeno za identifikaciju uredjaja po imenu umjesto po ID-u.. Prazni apostrofi znace da ignorisemo ovaj parametar, jer koristimo ID za detekciju

        deadzone: 0.5 #za analogne palice, svi pomaci palice manji od 50% od centra se ignorišu,Moraš da je pomeriš više od 0.5 (ili manje od -0.5) da bi se nešto dogodilo. Time se ogradjujemo od nesavrsenosti palice koje mogu da detektuju poket iako mi nismo nista uradili

        autorepeat_rate: 20.0 # bez ovo autorepeat-a joy_node šalje poruku samo kada se nešto promeni (npr. pomeriš palicu ili pritisneš taster). 
                              #ovako ponavlja poruku 20 puta u sekundi, posljednju koja je procitana
                              
        sticky_buttons: false # dugmad kao preklopnici, da je bilo true, to bi znacilo da jedno pritiskanje dugmeta komanda na ON, drugim pritiskanjem  na OFF
        coalesce_interval_ms: 1 #Vreme u milisekundama u kojem se višestruki ulazi kombinuju u jednu poruku.1ms znači da se gotovo svaka promena odmah prosleđuje, praktično bez odlaganja.
                                
                               # OS joy_node čeka određeni kratki period (npr. 1ms) da vidi da li dolaze još događaja, kako bi ih složio u jednu kompletnu poruku (sensor_msgs/msg/Joy).

                               # To smanjuje broj ROS poruka i povećava kvalitet podataka
                                #ako npr. pomjeramo jostick dijagonalno on prvo zabiljezi ulaz pomeranja po x osi pa malo saceka 1ms pa zabiljezi pomjeraj po y osi
                                #i zajedno posalje na kraju tako da se zap pomjeri dijagonalno objekat
                                